<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        echo $class;
        if ($classes === null) {
            $classes = array(
                'alchemyservice' => '/sentiment/alchemySentiment.php',
                'facebookservice' => '/social/facebookService.php',
                'financialservice' => '/financial/financialService.php',
                'financialserviceutility' => '/financial/financialServiceUtility.php',
                'googleplusservice' => '/social/googlePlusService.php',
                'redditservice' => '/social/redditService.php',
                'sentimentservice' => '/sentiment/sentiment.php',
                'service' => '/service/service.php',
                'socialservice' => '/social/socialService.php',
                'stockentry' => '/financial/stockEntry.php',
                'stocklyticsservice' => '/financial/stocklyticsService.php',
                'twitterservice' => '/social/twitterService.php',
                'yahooservice' => '/financial/yahooService.php'
            );
        }

        $cn = strtolower($class);

        if (isset($classes[$class])) {
            require __DIR__ . $classes[$class];
        }
     }
);
// @codeCoverageIgnoreEnd